---
# Ansible connectivity definitions
# eAPI connectivity via HTTPS is specified (as opposed to CLI via SSH)
ansible_connection: ansible.netcommon.httpapi
# Specifies that we are indeed using Arista EOS
ansible_network_os: arista.eos.eos
# User escalation (to enter enable mode)
ansible_become: true
ansible_become_method: enable
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false

custom_platform_settings:
  - platforms:
      - cEOS-lab
    management_interface: Management0

# Common AVD group variables
fabric_name: FABRIC

# Disable documentation generation
eos_designs_documentation:
  enable: false
eos_cli_config_gen_documentation:
  enable: false

# Define underlay and overlay routing protocol to be used
underlay_routing_protocol: ebgp
overlay_routing_protocol: ebgp

# BGP peer groups passwords
bgp_peer_groups:
  # all passwords set to "arista"
  evpn_overlay_peers:
    password: Q4fqtbqcZ7oQuKfuWtNGRQ==
  ipv4_underlay_peers:
    password: 7x4B4rnJhZB438m9+BrBfQ==
  mlag_ipv4_underlay_peer:
    password: 4b21pAdCvWeAqpcKDFMdWw==

# Set default uplink, downlink, and MLAG interfaces based on node type
default_interfaces:
  - types: [spine]
    platforms: [default]
    uplink_interfaces: [Ethernet1-2]
    downlink_interfaces: [Ethernet2-8]
  - types: [l3leaf]
    platforms: [default]
    uplink_interfaces: [Ethernet2, Ethernet3]
    mlag_interfaces: [Ethernet1, Ethernet6]
    downlink_interfaces: [Ethernet8]

# DNS Server
dns_settings:
  servers:
    - ip_address: 1.1.1.1

# NTP Servers IP or DNS name, first NTP server will be preferred, and sourced from Management VRF
ntp_settings:
  server_vrf: use_mgmt_interface_vrf
  servers:
    - name: 0.pool.ntp.org

mgmt_interface_vrf: default

custom_structured_configuration_eos_cli: |
    username admin privilege 15 role network-admin secret 5 $1$5O85YVVn$HrXcfOivJEnISTMb6xrJc.
    username arista privilege 15 role network-admin secret 5 $1$4VjIjfd1$XkUVulbNDESHFzcxDU.Tk1
    username arista ssh-key ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCrdG/8H6s9aEZM3KlnGOG1ir6fGBvBLwuYgFHW2Lq6xkRHgVAu4cLEUHqzl7TzQsdWoih8FZnzgDH3UzK6v3kaDd4FycydpjI0IXQ9+q1Rw9JDa5B0CyvTkoaE5xbwDZQ14+6X4Q8WVrCc2fn7gSYYyBFY7hd+qsb4aH8ezsEqR4OssP+0N1+6xJdlepK/ry0+scOUeaB2d5JLuOpnveN4AkOXrKdRymM2jh95eI8XhpcHjD0JqwHo5/RtOGFL+VVRe+QW8BGpUIFYHggpVGfxz0qFL/y2B/cdrs6oDEs9kLeG86tWT1+ZoMf0SYB3658aS1ba1TQcTNmQw18ArxsB arista@aap-demo-1-6d679806-eos
    !
    management api http-commands
      no shutdown
    !
    daemon TerminAttr
      exec /usr/bin/TerminAttr -cvcompression=gzip -smashexcludes=ale,flexCounter,hardware,kni,pulse,strata -ingestexclude=/Sysdb/cell/1/agent,/Sysdb/cell/2/agent -cvaddr=192.168.0.5:9910 -cvauth=token,/tmp/token -cvvrf=default -taillogs -disableaaa
      no shutdown
    !