---
version: 3

images:
  base_image:
    name: ghcr.io/ansible-community/community-ee-minimal:2.21.3-1

dependencies:
  python_interpreter:
    package_system: python314
    python_path: /usr/bin/python3.14

  galaxy: requirements.yml

  python: requirements.txt
