---
# validate.yml

- name: Test configuration
  hosts: htft-spine1
  gather_facts: false
  vars:
    avd_catalogs_enabled: false
    anta_runner_timeout: 15
    structured_dir: "{{ playbook_dir }}/intended/structured_configs"
    anta_catalogs: "{{ playbook_dir }}/anta/user_catalog/zero-touch.yml"
  tasks:
    - name: Validate the network
      ansible.builtin.import_role:
        name: arista.avd.anta_runner
