---
- name: Build and Deploy configuration
  hosts: FABRIC
  gather_facts: false
  vars_files:
    - ../group_vars/vault.yml
  tasks:

    - name: Generate AVD Structured Configurations and Fabric Documentation
      ansible.builtin.import_role:
        name: arista.avd.eos_designs

    - name: Generate Device Configurations and Documentation
      ansible.builtin.import_role:
        name: arista.avd.eos_cli_config_gen

    - name: Generate AVD Structured Configurations and Fabric Documentation
      ansible.builtin.import_role:
        name: arista.avd.cv_deploy
      vars:
        cv_server: aap-demo-1-083b8912-eos.topo.testdrive.arista.com
        cv_run_change_control: true
